// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.

// CHECK: #[[$ATTR_0:.+]] = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
// RUN: triton-shared-opt --triton-arith-to-linalg %s | FileCheck %s
module {
// CHECK-LABEL:   func.func @kernel(
// CHECK-SAME:  %[[VAL_0:.*]]: tensor<32x64x128x!tt.ptr<bf16>>, %[[VAL_1:.*]]: tensor<32x128x256x!tt.ptr<bf16>>, %[[VAL_2:.*]]: tensor<32x64x256x!tt.ptr<bf16>>, %[[VAL_3:.*]]: tensor<32x64x256x!tt.ptr<bf16>>, %[[VAL_4:.*]]: i32, %[[VAL_5:.*]]: i32, %[[VAL_6:.*]]: i32, %[[VAL_7:.*]]: i32, %[[VAL_8:.*]]: i32, %[[VAL_9:.*]]: i32) {
// CHECK:           %[[VAL_10:.*]] = arith.constant 0.000000e+00 : bf16
// CHECK:           %[[VAL_11:.*]] = tt.load %[[VAL_0]] : tensor<32x64x128x!tt.ptr<bf16>>
// CHECK:           %[[VAL_12:.*]] = tt.load %[[VAL_1]] : tensor<32x128x256x!tt.ptr<bf16>>
// CHECK:           %[[VAL_13:.*]] = tt.load %[[VAL_2]] : tensor<32x64x256x!tt.ptr<bf16>>
// CHECK:           %[[VAL_14:.*]] = tensor.empty() : tensor<32x64x256xbf16>
// CHECK:           %[[VAL_15:.*]] = linalg.fill ins(%[[VAL_10]] : bf16) outs(%[[VAL_14]] : tensor<32x64x256xbf16>) -> tensor<32x64x256xbf16>
// CHECK:           %[[VAL_16:.*]] = linalg.batch_matmul ins(%[[VAL_11]], %[[VAL_12]] : tensor<32x64x128xbf16>, tensor<32x128x256xbf16>) outs(%[[VAL_15]] : tensor<32x64x256xbf16>) -> tensor<32x64x256xbf16>
// CHECK:           %[[VAL_17:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel", "parallel", "parallel"]} ins(%[[VAL_13]], %[[VAL_16]] : tensor<32x64x256xbf16>, tensor<32x64x256xbf16>) outs(%[[VAL_13]] : tensor<32x64x256xbf16>) {
// CHECK:           ^bb0(%[[VAL_18:.*]]: bf16, %[[VAL_19:.*]]: bf16, %[[VAL_20:.*]]: bf16):
// CHECK:             %[[VAL_21:.*]] = arith.addf %[[VAL_18]], %[[VAL_19]] : bf16
// CHECK:             linalg.yield %[[VAL_21]] : bf16
// CHECK:           } -> tensor<32x64x256xbf16>
// CHECK:           tt.store %[[VAL_3]], %[[VAL_17]] : tensor<32x64x256x!tt.ptr<bf16>>
// CHECK:           return
// CHECK:         }
  tt.func @kernel(
    %arg0: tensor<32x64x128x!tt.ptr<bf16>>, %arg1: tensor<32x128x256x!tt.ptr<bf16>>, %arg2: tensor<32x64x256x!tt.ptr<bf16>>, %arg3: tensor<32x64x256x!tt.ptr<bf16>>
  )
  {
    %0 = tt.load %arg0: tensor<32x64x128x!tt.ptr<bf16>>
    %1 = tt.load %arg1: tensor<32x128x256x!tt.ptr<bf16>>
    %2 = tt.load %arg2: tensor<32x64x256x!tt.ptr<bf16>>
    %3 = tt.dot %0, %1, %2 : tensor<32x64x128xbf16> * tensor<32x128x256xbf16> -> tensor<32x64x256xbf16>
    tt.store %arg3, %3 : tensor<32x64x256x!tt.ptr<bf16>>
    tt.return
  }
}
